### ISSUE TITLE
ultima versione non funzionante

### ISSUE THREAD

**Issue by sicuro85** [Pirate-Crew/IPTV-Extreme#1]
da quando è stata inserita la cartella part_list il processo termina senza aver trovato nessuna lista

**Comment by Armax** [comment]
può essere che non è riuscito a trovarne su quel server, prova con un'altro, ho testato l'ultima versione contro un server fallato e ha funzionato

**Comment by sicuro85** [comment]
ho provato con vari server e da sempre la stessa cosa, dimmi una cosa ma come si fa a capire se un server è fallato o meno???

**Comment by Armax** [comment]
Provando ad attaccarlo, non essendo una vera e propria falla del cms

**Comment by sicuro85** [comment]
Ma l'attacco avviene alle liste o al server?

Inviato da iPhone

**Comment by ludo237** [comment]
@sicuro85 al server. Non possiamo offrire liste di server direttamente dalla repository ufficiale, è illegale e non vogliamo essere coinvolti. Sicuramente ci sono alcune liste in giro di server affetti dalla falla che usiamo.

**Comment by sicuro85** [comment]
Non mi sono spiegato bene, io chiedevo, ma con questa procedura si tenta il login al sito del server oppure fa i tentativi di creare i file m3u con nome utente e password uguali??

**Comment by samael81** [comment]
nome utente e password, ti ricordo che usufruire dei file m3u generati è illegale, non solo per chi effettua lo stream ma anche per chi ne usufruisce, ci sono stai da poco sequestri  e controlli in tutta italia e sospensione di molti dei server che davano questo servizio illegale :) Quindi ti consiglio di usarlo solo a scopo informativo/studio

Samael

**Comment by sicuro85** [comment]
Era solo per capire, sono consapevole dell'illegalità infatti non uso mai i file generati...

**Comment by Armax** [comment]
I file .m3u contengono una serie di link .ts con i collegamenti ai canali, sicchè ogni file .m3u contiene una combinazione user:passwd valida
