### ISSUE TITLE
errore compilazione iptv.cpp

### ISSUE THREAD

**Issue by elviramazzola** [Pirate-Crew/IPTV-Extreme#2]
quando compilo il file iptv.cpp mi da questo errore:

~/Scrivania/IPTV-Extreme-master $ g++ iptv.cpp  -o iptv -lcurl -lpthread
In file included from /usr/include/c++/4.9/thread:35:0,
                 from iptv.cpp:10:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
iptv.cpp: In function ‘void\* attack(void_)’:
iptv.cpp:36:25: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::string&)’
     ifstream infile(list);
                         ^
iptv.cpp:36:25: note: candidates are:
In file included from iptv.cpp:8:0:
/usr/include/c++/4.9/fstream:470:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char\* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/4.9/fstream:470:7: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char_’
/usr/include/c++/4.9/fstream:456:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.9/fstream:456:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.9/fstream:430:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:430:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
iptv.cpp:56:38: error: no matching function for call to ‘std::basic_ofstream<char>::basic_ofstream(std::string&)’
                 ofstream out(filename);
                                      ^
iptv.cpp:56:38: note: candidates are:
In file included from iptv.cpp:8:0:
/usr/include/c++/4.9/fstream:643:7: note: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ofstream(const char\* __s,
       ^
/usr/include/c++/4.9/fstream:643:7: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.9/fstream:628:7: note: std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ofstream(): __ostream_type(), _M_filebuf()
       ^
/usr/include/c++/4.9/fstream:628:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.9/fstream:602:11: note: std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.9/fstream:602:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::basic_ofstream<char>&’
iptv.cpp: In function ‘int main()’:
iptv.cpp:81:37: error: ‘strcpy’ was not declared in this scope
     strcpy(serverstr, server.c_str());

**Comment by samael81** [comment]
Ciao scusa l'intrusione io ho risolto in questo modo:

g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11

inoltre nel file iptv.cpp ho aggiunto
#include cstring

dopo queste piccole modifiche funziona tutto perfettamente 

Saluti
Samael

**Comment by Kingem39p** [comment]
salve, ringrazio l'utente samael81, avevo lo stesso problema pure io. Una volta fatta questa procedura però, mi esce il seguente errore: cc1plus: error: unrecognized command line option "-std=c++11"

se mi direste la soluzione ve ne sarei grato, grazie mille.

**Comment by samael81** [comment]
Ciao prova con l'altra opzione disponibile nell'errore

-std=gnu++11

Ciao

**Comment by Kingem39p** [comment]
grazie ancora una volta, ma chiedo scusa, mi dà ancora un'altro errore simile al precedente: cc1plus: error: unrecognized command line option "-std=gnu++11"

come se non trovasse l'opzione -std. come posso fare? grazie.

**Comment by samael81** [comment]
mi fai gentilmente vedere tutto il log di errore della compilazione?

**Comment by Kingem39p** [comment]
Si, ecco a te: 

[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11
cc1plus: error: unrecognized command line option "-std=c++11"
[root@HomeJack ~]# nano iptv.cpp 
[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=gnu++11
cc1plus: error: unrecognized command line option "-std=gnu++11"
[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11
cc1plus: error: unrecognized command line option "-std=c++11"
[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=gnu++11
cc1plus: error: unrecognized command line option "-std=gnu++11"

**Comment by samael81** [comment]
ecco a te, la colpa è di g++ a seconda della versione devi usare una delle sue opzioni, prova a controllare se è installato g++ e che versione ti ricodo che il pacchetto è gcc

In versions pre-G++ 4.7, you'll have to use -std=c++0x, for more recent versions you can use -std=c++11.

in extremis se proprio non funziona ho trovato anche questa soluzione 

I also got same error, compiling with -D flag fixed it, Try this:
g++ -Dstd=c++11

spero risolvi :)

**Comment by Kingem39p** [comment]
allora, grazie mille per l'aiuto. facendo g++, mi dice "g++: no input files", quindi teoricamente dovrebbe essere installato. Parlando della versione, ho eseguito il comando yum install gcc-c++, ed il pacchetto è chiamato gcc-c++-4.4.7-16.el6.x86_64. ho provato ad usare sia -std=c++0x, sia -Dstd=c++11 (al posto del semplice -std=c++11), ma senza nessun risultato positivo. 

Qui di seguito gli errori:

con -Dstd=c++1

[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -Dstd=c++11
iptv.cpp:7:23: error: curl/curl.h: No such file or directory
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/thread:35,
                 from iptv.cpp:10:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iosfwd:41,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from iptv.cpp:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stringfwd.h:42: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stringfwd.h:42: error: expected unqualified-id before ‘++’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:44,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/postypes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iosfwd:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from iptv.cpp:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cstddef:49: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cstddef:49: error: expected unqualified-id before ‘++’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/postypes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iosfwd:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from iptv.cpp:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:65: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:65: error: expected unqualified-id before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:139: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:139: error: expected unqualified-id before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:245: error: ‘::wcstold’ has not been declared
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:254: error: ‘::wcstoll’ has not been declared
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:255: error: ‘::wcstoull’ has not been declared
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:260: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cwchar:260: error: expected unqualified-id before ‘++’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iosfwd:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:39,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from iptv.cpp:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/postypes.h:70: error: expected ‘{’ before ‘++’ token
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/postypes.h:70: error: expected unqualified-id before ‘++’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from iptv.cpp:5:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/exception:35: error: expected declaration before end of line

con -std=c++0x

[root@HomeJack ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++0x
iptv.cpp:7:23: error: curl/curl.h: No such file or directory
iptv.cpp: In function ‘void\* attack(void*)’:
iptv.cpp:40: error: ‘CURL’ was not declared in this scope
iptv.cpp:40: error: ‘curl’ was not declared in this scope
iptv.cpp:41: error: ‘CURLcode’ was not declared in this scope
iptv.cpp:41: error: expected ‘;’ before ‘res’
iptv.cpp:46: error: ‘curl_easy_init’ was not declared in this scope
iptv.cpp:50: error: ‘CURLOPT_URL’ was not declared in this scope
iptv.cpp:50: error: ‘curl_easy_setopt’ was not declared in this scope
iptv.cpp:51: error: ‘CURLOPT_WRITEFUNCTION’ was not declared in this scope
iptv.cpp:52: error: ‘CURLOPT_WRITEDATA’ was not declared in this scope
iptv.cpp:53: error: ‘res’ was not declared in this scope
iptv.cpp:53: error: ‘curl_easy_perform’ was not declared in this scope
iptv.cpp:61: error: ‘curl_easy_cleanup’ was not declared in this scope

se ti chiedi se curl è installato posso confermarti di si. "curl-7.19.7-46.el6.x86_64 è già installato e aggiornato all'ultima versione"

**Comment by samael81** [comment]
io uso centos quindi sono più che certo che funziona anche su redhat

yum install gcc

e riparti da capo :)

**Comment by Kingem39p** [comment]
Ho appena finito di installare tutto ed eseguito g++ con il tuo metodo, ovvero aggiungendo #include <cstring> e -std=c++11, ma purtroppo senza nessuna conclusione.

mi spunta il solito errore: cc1plus: error: unrecognized command line option "-std=c++11"

p.s: ho cambiato macchina, l'OS è CentOS 6.6 x64

**Comment by Kingem39p** [comment]
scusatemi! 

in CentOS 5 e CentOS 6.6, gcc è in versione 4.4.7. Questa versione da problemi nella compilazione del file "iptv.cpp", quindi si risolve scaricandone una più recente.

qui di seguito una brevissima guida: http://ask.xmodulo.com/upgrade-gcc-centos.html

adesso, però, eseguendo la compilazione ho questo problema:

[root@VS18075-80965 IPTV-Extreme-master]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11
iptv.cpp:7:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.
[root@VS18075-80965 IPTV-Extreme-master]# 

come potrei risolvere il problema? 

grazie mille!

**Comment by samael81** [comment]
ora l'errore sembra di curl, hai per caso installato le development tools su centos?

yum groupinstall "Development Tools"

fallo e poi riprova

**Comment by Kingem39p** [comment]
allora, ho appena rifatto il processo, ma con CentOS 7.

funziona tutto, tranne appunto questo errore di curl. ho installato development tools, ma il solito errore: 

[root@VS18075-80965 ~]# g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11
iptv.cpp:7:23: fatal error: curl/curl.h: File o directory non esistente
 #include <curl/curl.h>
                       ^
compilation terminated.

**Comment by samael81** [comment]
Allora installa

libcurl-7.29.0-25.el7.centos.x86_64
libcurl-devel-7.29.0-25.el7.centos.x86_64

e riprova ora dovremmo esserci cmq anche io sto usando centos7

**Comment by samael81** [comment]
libcurl-devel-7.29.0-25.el7.centos.x86_64

**Comment by Kingem39p** [comment]
perfetto, compilato senza nessun errore! grazie mille samael81!

**Comment by samael81** [comment]
finalmente! 

Sono contento di essere riuscito ad aiutarti :)

**Comment by samael81** [comment]
king mi contatti via mail 1981samael1981@gmail.com

grazie

**Comment by Armax** [comment]
Grazie mille :) chiudo
