### ISSUE TITLE
IPTV-Extreme error

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV-Extreme#3]
salve, qualsiasi link io metta ricevo sempre lo stesso errore.

[i] Starting threads...
Starting thread: 0
Starting thread: 1
Starting thread: 2
Starting thread: 3
Starting thread: 4
Starting thread: 5
Starting thread: 6
Starting thread: 7
Starting thread: 8
Starting thread: 9
Starting thread: 10
Starting thread: 11
Starting thread: 12
Starting thread: 13
Starting thread: 14
Starting thread: 15
Starting thread: 16
[i] no output is showed for faster cracking, just wait until exit
[i] you will see cracked channel in the output directory

**Comment by ludo237** [comment]
Ping @Armax

**Comment by Armax** [comment]
It's not an error, just wait until done

Il giovedì 21 gennaio 2016, Claudio Ludovico notifications@github.com ha
scritto:

**Comment by Kingem39p** [comment]
@Armax It happens like in a millisecond: ./iptv_extreme -> server url: [url] -> press Enter -> ERROR

then I think that are the servers, or I'm wrong?

**Comment by Armax** [comment]
maybe, can you please send me a more detailed report?

**Comment by Kingem39p** [comment]
@Armax yeah, here I did a gif: https://i.gyazo.com/e178438a436eebea9ac4af42f21f0528.gif

obvious that " link " does not work , but any url I put in this line , it give me this error

**Comment by Armax** [comment]
Did you try links from IPTV crawler?

Il venerdì 22 gennaio 2016, Kingem39p notifications@github.com ha scritto:

**Comment by Kingem39p** [comment]
@Armax if you mean iptv.py, yes. I execute the script with "python iptv.py" and then it scan the servers, after I read the list  scanned, and finally I copy the url in iptv_extreme.

**Comment by Kingem39p** [comment]
A solution?

**Comment by Kingem39p** [comment]
I need help!
