### ISSUE TITLE
come si usa?

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV-Extreme#4]
ho provato su windows e su ubuntu ,ho digitato la stringa nel prompt dei comandi va, se lo avvio con Dev-c++ o codeblocks mi da errore fatale "curl/curl.h".
Grazie

**Comment by Armax** [comment]
devi linkare curl e pthread con codeblock altrimenti puoi fare direttamente con il comando g++ iptv.cpp -o iptv_extreme -lcurl -lpthread su ubuntu

**Comment by Tonyrock90** [comment]
e con ubuntu non va---che intendi per linkare? devo mettere il link del sito da attaccare?

**Comment by Armax** [comment]
che errore ti da ubuntu? (comunque no per linkare intendo che nelle build option di codeblocks devi aggiungere pthread e curl)

**Comment by Tonyrock90** [comment]
in che modo li aggiungo? mi da errore a #include "curl/curl.h" devo inserire qualcosa prima di /curl.h?
cmq su ubuntu dice directory non valida , ho visto anche dei video sul web avviavano un file nel mio stesso modo bah

**Comment by Armax** [comment]
ti sei mosso con cd nella cartella in cui è presente il file iptv.cpp?

**Comment by Tonyrock90** [comment]
sisi... cd \indirizzo\scrivania\IPTV-Extreme-master

**Comment by Armax** [comment]
mi fai copia e incolla del comando che fai per compilare e l'output? mi sembra strano che non te lo compila o.O

**Comment by Tonyrock90** [comment]
su ubuntu?

**Comment by Armax** [comment]
si

**Comment by Tonyrock90** [comment]
g++ iptv.cpp -o iptv_extreme -lcurl -lpthread

**Comment by Tonyrock90** [comment]
faccio copia e incolla dal file readme

**Comment by Armax** [comment]
no intendevo dal terminale di ubuntu con relativo errore

**Comment by Tonyrock90** [comment]
tony@System:~$ cd \home/tony/Scrivania/IPTV-Extreme-master 
bash: cd: home/tony/Scrivania/IPTV-Extreme-master: File o directory non esistente
tony@System:~$ cd /home/tony/Scrivania/IPTV-Extreme-master
tony@System:~/Scrivania/IPTV-Extreme-master$ g++ iptv.cpp -o iptv_extreme -lcurl -lpthread
iptv.cpp:7:23: fatal error: curl/curl.h: File o directory non esistente
 #include "curl/curl.h"
                       ^
compilation terminated.
tony@System:~/Scrivania/IPTV-Extreme-master$

**Comment by Armax** [comment]
Non hai curl installato su ubuntu, fai sudo apt-get install libcurl-dev poi prova di nuovo a fare g++ iptv.cpp -o iptv_extreme -lcurl -lpthread

**Comment by Tonyrock90** [comment]
Il pacchetto libcurl-dev è un pacchetto virtuale fornito da:
  libcurl4-openssl-dev 7.35.0-1ubuntu2.5
  libcurl4-nss-dev 7.35.0-1ubuntu2.5
  libcurl4-gnutls-dev 7.35.0-1ubuntu2.5
È necessario sceglierne uno da installare.
E: Il pacchetto "libcurl-dev" non ha candidati da installare
tony@System:~$

**Comment by Armax** [comment]
fai sudo apt-get install libcurl4-openssl-dev

**Comment by Tonyrock90** [comment]
dopo varie configurazioni dice 
Configurazione di libssl-doc (1.0.1f-1ubuntu2.16)...
Elaborazione dei trigger per libc-bin (2.19-0ubuntu6.6)...
tony@System:~$ g++ iptv.cpp -o iptv_extreme -lcurl -lpthread
g++: error: iptv.cpp: File o directory non esistente
tony@System:~$ cd /home/tony/Scrivania/IPTV-Extreme-master
tony@System:~/Scrivania/IPTV-Extreme-master$ g++ iptv.cpp -o iptv_extreme -lcurl -lpthread
In file included from /usr/include/c++/4.8/thread:35:0,
                 from iptv.cpp:10:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
iptv.cpp: In function ‘void\* attack(void_)’:
iptv.cpp:36:25: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::string&)’
     ifstream infile(list);
                         ^
iptv.cpp:36:25: note: candidates are:
In file included from iptv.cpp:8:0:
/usr/include/c++/4.8/fstream:467:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char\* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/4.8/fstream:467:7: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char_’
/usr/include/c++/4.8/fstream:453:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:453:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8/fstream:427:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:427:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
iptv.cpp:56:38: error: no matching function for call to ‘std::basic_ofstream<char>::basic_ofstream(std::string&)’
                 ofstream out(filename);
                                      ^
iptv.cpp:56:38: note: candidates are:
In file included from iptv.cpp:8:0:
/usr/include/c++/4.8/fstream:640:7: note: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char_, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ofstream(const char\* __s,
       ^
/usr/include/c++/4.8/fstream:640:7: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.8/fstream:625:7: note: std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ofstream(): __ostream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:625:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8/fstream:599:11: note: std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8/fstream:599:11: note:   no known conversion for argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const std::basic_ofstream<char>&’
iptv.cpp: In function ‘int main()’:
iptv.cpp:81:37: error: ‘strcpy’ was not declared in this scope
     strcpy(serverstr, server.c_str());
                                     ^
tony@System:~/Scrivania/IPTV-Extreme-master$

**Comment by Armax** [comment]
prova g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11 or -std=gnu++11

**Comment by Tonyrock90** [comment]
g++: error: or: File o directory non esistente

**Comment by Armax** [comment]
g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11

**Comment by Tonyrock90** [comment]
tony@System:~/Scrivania/IPTV-Extreme-master$ g++ iptv.cpp -o iptv_extreme -lcurl -lpthread -std=c++11
iptv.cpp: In function ‘int main()’:
iptv.cpp:81:37: error: ‘strcpy’ was not declared in this scope
     strcpy(serverstr, server.c_str());
                                     ^
tony@System:~/Scrivania/IPTV-Extreme-master$

**Comment by Armax** [comment]
strano using namespace std; è presente, btw considerati tutti gli errori che ti da non ti conviene usare la versione in python?

**Comment by Tonyrock90** [comment]
non funziona proprio ... errore anche lì, percio' da windows ho deciso di installare ubuntu e nemmeno va

**Comment by Tonyrock90** [comment]
con windows partiva e si bloccata nella ricerca con l'errore ops qualcosa è andato storto

**Comment by Armax** [comment]
io l'ho provato a compilare sia su Os X che su Debian e non ho avuto problemi, per quello ti dico di usare la versione in python anzichè sbatterci troppo la testa

**Comment by Tonyrock90** [comment]
l'ho sbattuta da quando il pirata ha messo il video sul tubo.

**Comment by Armax** [comment]
il suo video non riguarda questa versione però

**Comment by Tonyrock90** [comment]
Si lo so.Ho provato anche la 1.2.3 e ho avuto un punto di merito ma....é pura sfiga nn va

**Comment by Tonyrock90** [comment]
l'altra versione alla finr mi da questo quando voglio installare i requirements 
creating /usr/local/lib/python2.7/dist-packages/pyprind

error: could not create '/usr/local/lib/python2.7/dist-packages/pyprind': Permission denied

Cleaning up...

**Comment by Tonyrock90** [comment]
ho usato il comando sudo chmod -R 777 /usr/local e mi ha rilasciato creating build/temp.linux-i686-2.7/psutil

i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=330 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-i686-2.7/psutil/_psutil_linux.o

psutil/_psutil_linux.c:12:20: fatal error: Python.h: File o directory non esistente

 #include <Python.h>

                    ^

compilation terminated.

error: command 'i686-linux-gnu-gcc' failed with exit status 1

**Comment by Tonyrock90** [comment]
ragazzi per piacere mi aiutate nell'issue #31
